//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageReply
    {
        public int ReplyId { get; set; }
        public string MessageText { get; set; }
        public System.DateTime SendAt { get; set; }
        public bool SentStatus { get; set; }
        public bool SeenStatus { get; set; }
        public int SenderId { get; set; }
        public int ReceiverId { get; set; }
        public int MessageId { get; set; }
    }
}
